version: 0.2
# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

#################################
# Runtime Environment Variables #
#################################

# env:
#   variables:
#     key: "value"
#     key: "value"
#   parameter-store:
#     key: "value"
#     key: "value"

phases:
    install:
        commands:
            - echo "Install phase"
            - npm i -g serverless
            # - node -v
            # - npm -v
            # - npm install
    pre_build:
        commands:
            - echo "Pre-build phase"
    build:
        commands:
            - echo "Build and deploy phase"
            - sls deploy --stage=$STAGE --region=us-east-2
    post_build:
        commands:
            - echo "Post-build phase"
            # - sam package --s3-bucket $BUILD_OUTPUT_BUCKET --template-file template.yml --output-template-file packaged.yml

##################################
# Build Artifacts to be uploaded #
##################################

artifacts:
    files:
        # list of local files relative to this build environment that will be added to the final artifact (zip)
        - .serverless/*
    discard-paths: yes
